server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///login_regist
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    protocol: smtp
    host: smtp.sina.com
    username: huoyan173236198@sina.com
    password: wentao173236198
dubbo:
  application:
    name: email_service
  registry:
    address: zookeeper://47.112.137.117:2181
  protocol:
    port: -1
  consumer:
    check: false